### PR TITLE
Upgrade shelljs

### PR DESCRIPTION
**Pull request by nickbrowne**
To test, run the various npm scripts which use different parts of the cakefile:
```
npm run build
npm run test
npm run prepublish
```
None should give any errors or any build output changes.

### CODE REVIEW

**Comment by mattptc** [comment]
I get a test failure on the branch and on main.
Followed the README and created the db. Test still failed.
Also tried with an older version of node.

```
FAILURES: Undone tests (or their setups/teardowns):
- db - pg - create doesnt send an error when a document is created
```

**Comment by nickbrowne** [comment]
> I get a test failure on the branch and on main.
> Followed the README and created the db. Test still failed.
> Also tried with an older version of node.

You might just need to `createdb sharejs_example` if you haven't already, slight gotcha

**Comment by mattptc** [comment]
I had to comment out the db host in `options.js`

```
// host: "/var/run/postgresql",
```

That probably works on Linux but the socket on MacOS must be different.  The default seems to work.

**Review by mattptc — APPROVED** [review]

**Comment by nickbrowne** [comment]
> That probably works on Linux but the socket on MacOS must be different. The default seems to work.

Ah yep, good to know.

**Pull request merged**
