### PR TITLE
Allow PG db adapter to accept a pool instead of a client

### PR DESCRIPTION
**Pull request by RohanM**
- See also: https://github.com/conversation/tc-share/pull/183

There are a couple of issues that impact ShareJS's resilience as an app. ShareJS uses in-memory state, which limits us to running only one node at a time. Additionally, when the db connection is lost no automatic reconnect is attempted. When this happens, we have to manually re-ship the app to resume service. We encounter this problem when an automatic GKE update is applied to the database, and it's also not great for the resilience of the app in general.

Our db connection is made via [node-postgres](https://node-postgres.com/). We currently make a client connection directly, but the library also offers a [`Pool`](https://node-postgres.com/apis/pool) class. `Pool` offers a `query()` convenience method that runs a query on the first available connection, while having the additional property of attempting reconnection if needed. Allow our pg adapter to accept either of a `Pool` or a `Client` so that we can make use of this.

### CODE REVIEW

**Comment by RohanM** [comment]
[Explicitly accept a pool instead of a client](https://trello.com/c/zV3izZAB/14579-explicitly-accept-a-pool-instead-of-a-client)

**Comment by nickbrowne** [comment]
Having a look at this now

**Comment by nickbrowne** [comment]
Took a bit to review since I was looking at https://github.com/conversation/tc-share/pull/183 and just understanding that also and trying to think if this has always been an issue or if we perhaps messed up the configuration at some point.

Cause I remember at one point we were using a different pg client and also preferring to connect to the unix socket rather than over TCP/IP... didn't manage to track down anything meaningful though.

For future reference (mostly for myself cause I'll probably find this comment again) the way you can "trick" the non native pg client into using the unix socket is to pass these options:
```
  let options = {
    host: "/run/postgresql",
    database: "sharejs_development",
    max: 5
  }
  ```

**Review by nickbrowne — APPROVED** [review]
Seems like a good idea, https://github.com/conversation/tc-share/pull/183 works well :+1:

**Pull request merged**
